catalogs:
  dev:
    '@sxzz/eslint-config': ^6.1.2
    '@sxzz/prettier-config': ^2.2.1
    '@sxzz/test-utils': ^0.5.5
    '@types/debug': ^4.1.12
    '@types/diff': ^7.0.2
    '@types/node': ^22.14.1
    bumpp: ^10.1.0
    eslint: ^9.25.1
    pkg-types: ^2.1.0
    prettier: ^3.5.3
    publint: ^0.3.12
    tsup: ^8.4.0
    tsx: ^4.19.3
    typescript: ~5.8.3
    unplugin-unused: ^0.4.4
    vitest: ^3.1.2

  docs:
    '@unocss/eslint-plugin': ^66.1.0-beta.12
    typedoc: ^0.28.3
    typedoc-plugin-markdown: ^4.6.2
    unocss: ^66.1.0-beta.12
    vite: ^6.3.2
    vitepress: ^1.6.3
    vitepress-plugin-group-icons: ^1.5.2
    vitepress-plugin-llms: ^1.1.0
    vue: ^3.5.13

  prod:
    ansis: ^3.17.0
    cac: ^6.7.14
    chokidar: ^4.0.3
    consola: ^3.4.2
    debug: ^4.4.0
    diff: ^7.0.0
    find-up-simple: ^1.0.1
    hookable: ^5.5.3
    rolldown: 1.0.0-beta.8-commit.d984417
    rolldown-plugin-dts: ^0.8.3
    tinyexec: ^1.0.1
    tinyglobby: ^0.2.13
    unconfig: ^7.3.2

onlyBuiltDependencies:
  - esbuild
