catalogs:
  dev:
    '@sxzz/eslint-config': ^6.2.0
    '@sxzz/prettier-config': ^2.2.1
    '@sxzz/test-utils': ^0.5.5
    '@types/debug': ^4.1.12
    '@types/diff': ^7.0.2
    '@types/node': ^22.15.3
    bumpp: ^10.1.0
    eslint: ^9.25.1
    pkg-types: ^2.1.0
    prettier: ^3.5.3
    publint: ^0.3.12
    tsup: ^8.4.0
    tsx: ^4.19.4
    typescript: ~5.8.3
    unplugin-unused: ^0.4.4
    vitest: ^3.1.2
  docs:
    '@unocss/eslint-plugin': ^66.1.0-beta.12
    typedoc: ^0.28.3
    typedoc-plugin-markdown: ^4.6.3
    unocss: ^66.1.0-beta.12
    vite: ^6.3.3
    vitepress: ^1.6.3
    vitepress-plugin-group-icons: ^1.5.2
    vitepress-plugin-llms: ^1.1.1
    vue: ^3.5.13

onlyBuiltDependencies:
  - esbuild
